### PR TITLE
[MASSEMBLY-617] add ability to give a fileSuffix to a FileSet

### PR DESCRIPTION
**Pull request by tcollignon**
Hi

In order to fix https://issues.apache.org/jira/browse/MASSEMBLY-617, I need to add a capability to add file suffix to a FileSet
This PR add this feature, but it need https://github.com/sonatype/plexus-archiver/pull/25 and https://github.com/sonatype/plexus-io/pull/7

Tell me if something goes wrong

### CODE REVIEW

**Comment by plamentotev** [comment]
The same functionality can be achieved using `FileMapper`. It would be great if you consider implementing it using file mappers as that would solve other uses cases as well (for example [MASSEMBLY-886](https://issues.apache.org/jira/projects/MASSEMBLY/issues/MASSEMBLY-886)). For example on how to implement such functionality you can take a look here - https://www.mojohaus.org/xml-maven-plugin/examples/transform-change-extension.html

**Comment by tcollignon** [comment]
Hi

Thank for your tips @plamentotev, I will take a look at FileMapper and see if I can update this PR to use directly it.

**Comment by tcollignon** [comment]
I don't know a lot of things in this plugin. The InputStreamTransformer is not the same of the FileMapper right ?

**Comment by plamentotev** [comment]
No. `InputStreamTransformer` modifies the content of the file (like changing the line ending). `FileMapper` changes the file name based on some logic (so it is actually a file name mapper). You need to make a similar change to one already did. But instead of String you need to configure an array of [`org.codehaus.plexus.components.io.filemappers.FileMapper`](https://github.com/codehaus-plexus/plexus-io/blob/master/src/main/java/org/codehaus/plexus/components/io/filemappers/FileMapper.java). And after that you need to propagate the array to `AbstractPlexusIoResourceCollection`. I don't think `BaseFileSet` accepts `FileMapper[]` so I think you need to change it as well.

Hope this helps.

**Comment by tcollignon** [comment]
Thx for your precious help, I will try to implement this

**Comment by tcollignon** [comment]
This PR can be closed, because I work in #5

**Pull request closed without merging**
