### PR TITLE
MASSEMBLY-941 keep file permission in Reproducible mode

### PR DESCRIPTION
**Pull request by hboutemy**
https://issues.apache.org/jira/browse/MASSEMBLY-941

### CODE REVIEW

**Comment by michael-o** [comment]
Use %n

**Comment by hboutemy** [comment]
@michael-o what does "use %n" mean, please?

**Comment by pzygielo** [comment]
> @michael-o what does "use %n" mean, please?

In `String.format` instead of `\n` I presume...

**Comment by michael-o** [comment]
> > @michael-o what does "use %n" mean, please?
> 
> In `String.format` instead of `\n` I presume...

Almost, it is replaced with the platform line separator.

**Comment by hboutemy** [comment]
ok, but how does it relate to this PR?

In the current PR, Windows is a pain not as usual because it has specific newlines, but because it can't detect executable files on filesystem (`100644 executable.txt`) (notice that Unix is a pain because it has 2 representations: `100755 executable.txt`and `100775 executable.txt`)

**Comment by michael-o** [comment]
> ok, but how does it relate to this PR?
> 
> In the current PR, Windows is a pain not as usual because it has specific newlines, but because it can't detect executable files on filesystem (`100644 executable.txt`) (notice that Unix is a pain because it has 2 representations: `100755 executable.txt`and `100775 executable.txt`)

It is not related, I just noticed it. If you really just need a LF then a comment should tell about your intent.

**Comment by hboutemy** [comment]
> It is not related, I just noticed it. If you really just need a LF then a comment should tell about your intent.

AFAIK there is nothing related to LF in this PR, then I suppose I should just ignore that comment that looks to me just a mistake (no pun intended, it happens to me also to completely be out of context because I misread something): if you think there is one place in the PR where it applies, please precise the location

**Comment by michael-o** [comment]
> > It is not related, I just noticed it. If you really just need a LF then a comment should tell about your intent.
> 
> AFAIK there is nothing related to LF in this PR, then I suppose I should just ignore that comment that looks to me just a mistake (no pun intended, it happens to me also to completely be out of context because I misread something): if you think there is one place in the PR where it applies, please precise the location

Agreed.

**Pull request merged**
