### PR TITLE
MASSEMBLY-945 - speed improvements

### PR DESCRIPTION
**Pull request by gnodet**
This PR only makes sense with 
https://github.com/codehaus-plexus/plexus-utils/pull/106
https://github.com/codehaus-plexus/plexus-io/pull/33
https://github.com/codehaus-plexus/plexus-archiver/pull/157
https://github.com/apache/maven-common-artifact-filters/pull/15

... but if I add the snapshot upgrades, the checks won't pass anymore ;-)

### CODE REVIEW

**Review by cstamas — APPROVED** [review]

**Comment by elharo** [comment]
have you measured the improvements? if so, what are the numbers?

**Comment by bmarwell** [comment]
> have you measured the improvements? if so, what are the numbers?

Null-length arrays are known to be faster since at least 2013 iirc.

* https://shipilev.net/blog/2016/arrays-wisdom-ancients/ (updated 2016)
* https://stackoverflow.com/a/29444594/1549977 (from 2013)

In my opinion measurements are not needed here because of this.

**Review by bmarwell — APPROVED** [review]

**Comment by elharo** [comment]
Far more often than not, microoptimizations like this result in no measurable impact. All claims of performance improvements need numbers.

**Comment by bmarwell** [comment]
> Far more often than not, microoptimizations like this result in no measurable impact. All claims of performance improvements need numbers.

https://github.com/codehaus-plexus/plexus-io/pull/33#discussion_r530614310

**Comment by gnodet** [comment]
The speed gain may be negligible for this PR, it does not matter much.
However, I'd like the other PR referenced above to get merged, so that we can upgrade to those new versions to have a *non negligible* performance gain.

**Review by olamy — APPROVED** [review]

**Review by slachiewicz — APPROVED** [review]

**Comment by eolivelli** [comment]
+1

**Pull request merged**
