### PR TITLE
[MASSEMBLY-775] for review

### PR DESCRIPTION
**Pull request by struberg**
hi! up for review before I gonna commit it.

### CODE REVIEW

**Comment by rfscholte** [comment]
I've replaced Easymock with Mockito, so this PR needs to be updated

**Review by elharo — COMMENTED** [review]
do you want to refresh this?

**Comment by yuhaowin** [comment]
> do you want to refresh this?

The changes seem to have been merged into master, could close this pr and [issue](https://issues.apache.org/jira/browse/MASSEMBLY-775)

**Comment by jira-importer** [comment]
Resolve #979

**Pull request closed without merging**
